### ISSUE TITLE
Make password argument optional

### ISSUE THREAD

**Issue by ScreamingHawk** [jleni/wallet-decrypt#4]
Passing a password through as an argument is poor security practice (as your password becomes stored in your `.bash_history` etc). 

I suggest that the `password` argument be made optional (so it can still be provided for scripts if needed) and a user request is made using `input('Please enter password: ')` or similar if it is not supplied. 

This script is great. Thanks so much!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201680498146181/1201680652410297) by [Unito](https://www.unito.io)

**Comment by jleni** [comment]
You are right. I will try to improve that. 
To be fair, I used it only once and transferred everything out so it was not a problem in my case, but I get your point. Thanks!
